name: Build after push to master

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore FastColoredTextBox.sln
    - name: Build
      run: dotnet build --no-restore FastColoredTextBox.sln
    - name: Test
      run: dotnet test --no-build --verbosity normal  FastColoredTextBox.sln
    - name: Package
      run: dotnet test --no-build --verbosity normal  FastColoredTextBox.sln